- name: Prepara o node-exporter para expor métricas nos nós conhecidos
  hosts: all
  vars:
    control_user: prometheus
    exporter_binary: /usr/local/sbin/node_exporter
  tasks:
    - name: Cria o usuário responsável pelas métricas
      ansible.builtin.user:
        name: "{{ control_user }}"
        password: '!'
        system: true
        create_home: false

    - name: Faz o download do node_exporter
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
        mode: 0775
        owner: "{{ control_user }}"
        group: "{{ control_user }}"
        dest: /tmp/node_exporter.tar.gz

    - name: Cria o diretório para a extração
      ansible.builtin.file:
        path: /tmp/node_exporter
        mode: 0775
        owner: "{{ control_user }}"
        group: "{{ control_user }}"
        state: directory

    - name: Faz a extração dos arquivos
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/node_exporter
        mode: 0775
        owner: "{{ control_user }}"
        group: "{{ control_user }}"
        extra_opts:
          - --strip-components=1

    - name: Move o binário para o diretório correto
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/node_exporter/node_exporter
        dest: "{{ exporter_binary }}"
        mode: 0755
        owner: "{{ control_user }}"
        group: "{{ control_user }}"

    - name: Prepara o serviço do node_exporter
      ansible.builtin.template:
        src: service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0644
      notify: service_ok
  handlers:
    - name: Inicia o serviço do node_exporter
      ansible.builtin.systemd:
        name: node_exporter
        state: started
        enabled: true
      listen: service_ok
